version: '3.9'

services:
    db:
        image: mysql
        restart: always
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
        volumes:
            - mysql_db:/var/lib/mysql

    api:
        container_name: api_node
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file: ./.env
        ports:
            - 3300:$PORT
        environment:
            - PORT=$PORT
        depends_on:
            - db
        volumes:
            - .:/usr/src/app
volumes:
    mysql_db:
